import { oswald, urbanist } from "@/fonts";
import "./globals.css";
import type { Metadata } from "next";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Next Shoe Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
